[CronTab]
Schedule = "*/1 * * * *"

[Mysql]
Host = "127.0.0.1"
Port = "3306"
Username = "root"
Password = "abcd1234"
Database = "rss"

[Redis]
Address = "127.0.0.1:6379"
Password = ""

[Http]
Port = "10001"

[Proxy]
Address = "http://47.117.165.47:8123"
