[CronTab]
Schedule = "*/5 * * * *"

[Mysql]
Host = "mysql"
Port = "3306"
Username = "root"
Password = "abcd1234"
Database = "rss"

[Redis]
Address = "redis:6379"
Password = ""

[Http]
Port = "10002"

[Proxy]
Address = "http://47.117.165.47:8123"
